# Generated by Django 5.2.11 on 2026-07-08 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SUSELdapSourceSyncState",
            fields=[
                (
                    "ldap_source_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_modify_timestamp",
                    models.DateTimeField(verbose_name="Last processed modify timestamp in LDAP"),
                ),
            ],
            options={
                "db_table": "suse_ldapsyncstate",
            },
        ),
    ]
