# Generated by Django 5.2.11 on 2026-07-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ldap", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="suseldapsourcesyncstate",
            table="suse_source_ldap_state",
        ),
    ]
