# Generated by Django 5.2.11 on 2026-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SUSEProviderSyncState",
            fields=[
                (
                    "provider_id",
                    models.IntegerField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "last_modify_timestamp",
                    models.DateTimeField(verbose_name="Last processed modify timestamp in LDAP"),
                ),
            ],
            options={
                "db_table": "suse_provider_state",
            },
        ),
    ]
